#!/bin/bash

set -eu

DIR=$(dirname $(realpath $0))
OS_MIGRATE_DIR=$(realpath "$DIR/..")
if [ -t 1 ]; then
    CONTAINER_TTY="${CONTAINER_TTY:--ti}"
else
    CONTAINER_TTY="${CONTAINER_TTY:-}"
fi

if ! podman images | grep -q '^localhost/os_migrate_toolbox \+latest '; then
    pushd "$OS_MIGRATE_DIR"
    make toolbox-build
    popd
fi

IDX=0
while podman inspect os_migrate_$IDX &> /dev/null; do
    ((IDX++))
done || true

podman run \
       --name os_migrate_$IDX \
       --detach-keys='ctrl-^' \
       $CONTAINER_TTY \
       --rm \
       --net host \
       --security-opt label=disable \
       -v "$OS_MIGRATE_DIR:/root/os_migrate:z" \
       ${OS_MIGRATE_TOOLBOX_ARGS:-} \
       localhost/os_migrate_toolbox:latest \
       "$@"
