#!/bin/bash

set -eu

if [ -e /.os-migrate-toolbox ]; then
    echo "ERROR: You're already within an os-migrate toolbox container."
    echo "Calls to toolbox shouldn't be nested."
    exit 1
fi

DIR=$(dirname $(realpath $0))
OSM_DIR=$(realpath "$DIR/..")
if [ -t 1 ]; then
    CONTAINER_TTY="${CONTAINER_TTY:--ti}"
else
    CONTAINER_TTY="${CONTAINER_TTY:-}"
fi

if ! podman images | grep -q '^localhost/os_migrate_toolbox \+latest '; then
    pushd "$OSM_DIR"
    make toolbox-build
    popd
fi

IDX=0
while podman inspect os_migrate_$IDX &> /dev/null; do
    ((IDX++))
done || true

PASS_THROUGH_VARS=$(compgen -A variable | grep '^OS_MIGRATE_' | awk '{ print "-e " $0; }' | tr '\n' ' ' || true)

podman run \
       --name os_migrate_$IDX \
       --detach-keys='ctrl-^' \
       $CONTAINER_TTY \
       --rm \
       --net host \
       --security-opt label=disable \
       $PASS_THROUGH_VARS \
       -v /etc/resolv.conf:/etc/resolv.conf:ro \
       -v "$OSM_DIR:/root/os_migrate:z" \
       ${OS_MIGRATE_TOOLBOX_ARGS:-} \
       localhost/os_migrate_toolbox:latest \
       "$@"
