#!/bin/bash

set -eu

if [ -e /.os-migrate-toolbox ]; then
    echo "ERROR: You're already within an os-migrate toolbox container."
    echo "Calls to toolbox shouldn't be nested."
    exit 1
fi

DIR=$(dirname $(realpath $0))
OS_MIGRATE_DIR=$(realpath "$DIR/..")
if [ -t 1 ]; then
    CONTAINER_TTY_CREATE="${CONTAINER_TTY_CREATE:--ti}"
    CONTAINER_TTY_START="${CONTAINER_TTY_START:--i}"
else
    CONTAINER_TTY_CREATE="${CONTAINER_TTY_CREATE:-}"
    CONTAINER_TTY_START="${CONTAINER_TTY_START:-}"
fi

if ! podman images | grep '^localhost/os_migrate_toolbox \+latest '; then
    pushd "$OS_MIGRATE_DIR"
    make toolbox-build
    popd
fi

CONTAINER_IMAGE=${CONTAINER_IMAGE:-localhost/os_migrate_toolbox}
ROOTLESS_IMAGE_ID=$(podman inspect -f '{{.Id}}' $CONTAINER_IMAGE || true)
ROOTFUL_IMAGE_ID=$(sudo podman inspect -f '{{.Id}}' $CONTAINER_IMAGE || true)
if [ "$ROOTLESS_IMAGE_ID" != "$ROOTFUL_IMAGE_ID" ]; then
    echo "Refreshing rootful image $CONTAINER_IMAGE..."
    podman save $CONTAINER_IMAGE | sudo podman load
fi

[ -e /usr/lib/passwd ] && USR_LIB_PASSWD="-v /usr/lib/passwd:/usr/lib/passwd:ro" || USR_LIB_PASSWD=""
[ -e /usr/lib/group ] && USR_LIB_GROUP="-v /usr/lib/group:/usr/lib/group:ro" || USR_LIB_GROUP=""

IDX=0
while sudo podman inspect os_migrate_vagrant_$IDX &> /dev/null; do
    ((IDX++))
done || true
CONTAINER_NAME=os_migrate_vagrant_$IDX

mkdir -p $HOME/.vagrant.d
mkdir -p $HOME/.cache/libvirt
mkdir -p $HOME/.config/libvirt
mkdir -p $HOME/.local/share/libvirt/vagrant

sudo podman create \
    --name $CONTAINER_NAME \
    $CONTAINER_TTY_CREATE \
    --rm \
    --net host \
    --pid host \
    --privileged \
    --security-opt label=disable \
    -u $UID:$UID \
    -v $HOME/.vagrant.d:$HOME/.vagrant.d \
    -v $HOME/.cache/libvirt:$HOME/.cache/libvirt \
    -v $HOME/.config/libvirt:$HOME/.config/libvirt \
    -v $HOME/.local/share/libvirt:$HOME/.local/share/libvirt \
    -v $OS_MIGRATE_DIR:$OS_MIGRATE_DIR \
    \
    -v /dev/net:/dev/net:rw \
    -v /etc/passwd:/etc/passwd:ro \
    -v /etc/group:/etc/group:ro \
    -v /etc/libvirt:/etc/libvirt:ro \
    -v /lib/modules:/lib/modules:ro \
    -v /run/libvirt:/run/libvirt:shared \
    -v /var/lib/libvirt:/var/lib/libvirt \
    $USR_LIB_PASSWD \
    $USR_LIB_GROUP \
    \
    -e LC_ALL=C.UTF-8 \
    -e HOME="$HOME" \
    -e SHELL="$SHELL" \
    -e XDG_DATA_DIRS="$XDG_DATA_DIRS" \
    -w "$OS_MIGRATE_DIR/toolbox/vagrant" \
    ${OS_MIGRATE_VAGRANT_TOOLBOX_ARGS:-} \
    localhost/os_migrate_toolbox \
    "$@"

CONTAINER_FS=$(sudo podman mount $CONTAINER_NAME)
if [ -z "$CONTAINER_FS" ]; then
    echo "ERROR: Empty container filesystem root path, cannot initialize the container."
    exit 1
fi
sudo mkdir -p "${CONTAINER_FS}${HOME}/.cache"
sudo mkdir -p "${CONTAINER_FS}${HOME}/.config"
sudo mkdir -p "${CONTAINER_FS}${HOME}/.local/share"
sudo mkdir -p "${CONTAINER_FS}${OS_MIGRATE_DIR}"
sudo chown -R "$USER:" "${CONTAINER_FS}${HOME}"

sudo podman start $CONTAINER_NAME \
    $CONTAINER_TTY_START \
    -a \
    --detach-keys='ctrl-^'
