- name: start devstack
  ansible.builtin.shell: |
    cd /home/stack/devstack
    LOGFILE=/home/stack/devstack.log ./stack.sh 2>&1
  args:
    executable: /bin/bash
  changed_when: true
  become: true
  become_user: stack
