---
galaxy_info:
  author: os-migrate
  role_name: import_security_groups
  description: os-migrate resource
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - "34"
  galaxy_tags: ["osmigrate"]
dependencies:
  - role: os_migrate.os_migrate.prelude_dst
  - role: os_migrate.os_migrate.validate_resource_files
    vars:
      resource_files:
        - "{{ os_migrate_data_dir }}/security_groups.yml"
