---
galaxy_info:
  author: os-migrate
  role_name: validate_resource_files
  description: os-migrate resource validation
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - "34"
  galaxy_tags: ["osmigrate"]
dependencies: []
