import_workloads_keypair_private_path: "{{ os_migrate_data_dir }}/conversion/ssh.key"
import_workloads_timeout: 1800
import_workloads_cleanup_on_failure: true
import_workloads_boot_volume_prefix: os-migrate-
import_workloads_stop_before_migration: false
import_workloads_data_copy: true
import_workloads_filter:
  - regex: .*
