@startuml

skinparam LegendFontSize 10
skinparam NoteFontSize 9

title Pre-workload migration (workflow)

start

:[A] Export networks from src;

:[A] Export subnets from src;

if (Edits wanted?) then (yes)
    :Edit resource serializations;
else (no)
endif

:[A] Validate resource files;

:[A] Import networks to dst;

:[A] Import subnets to dst;

stop

legend bottom
    [A] = Ansible playbook from OS-Migrate
    src = source cloud
    dst = destination cloud
    --
    Diagram limited to networks and subnets for brevity.
endlegend

@enduml
