@startuml

skinparam ArrowFontColor darkred
skinparam CloudBorderColor gray
skinparam NodeBorderColor gray
skinparam NoteFontSize 9

title Pre-workload migration (data flow)

cloud Source {
    rectangle Resources as src_res
}

cloud Destination {
    rectangle Resources as dst_res
}

src_res -[hidden]right-> dst_res


node Migrator {
    file "Serialized\nresources" as ser_res
}

src_res -down-> ser_res : Export
ser_res -up->dst_res : Import

ser_res -down-> ser_res : Edit

@enduml
