@startuml

skinparam ArrowFontColor darkred
skinparam CloudBorderColor gray
skinparam ComponentBorderColor black
skinparam NodeBorderColor gray
skinparam LegendFontSize 10
skinparam NoteFontSize 9

title Workload migration (data flow)

cloud Source {
    rectangle "VMs+volumes" as src_res
    component "CH" as src_ch
}

cloud Destination {
    rectangle "VMs+volumes" as dst_res
    component "CH" as dst_ch
}

src_res -right-> src_ch
src_ch -right-> dst_ch : Binary data
dst_ch -right-> dst_res


node Migrator {
    file "Serialized\nmetadata" as ser_res
}

src_res .down.> ser_res : Metadata
ser_res -[dotted]up-> src_ch : Trigger binary\ndata migration
ser_res -[dotted]up-> dst_ch
ser_res .up.> dst_res : Create a VM using\nmetadata and\ncopied binary data

ser_res .down.> ser_res : Edit

legend bottom left
    CH = conversion host
endlegend

@enduml
