# Required vars:
# os_migrate_conversion_flavor_name

# Required if managing network creation/deletion:
# os_migrate_conversion_external_network_name

os_migrate_conversion_manage_network: true

os_migrate_conversion_net_name: os_migrate_conv

os_migrate_src_conversion_net_mtu: "{{ omit }}"
os_migrate_dst_conversion_net_mtu: "{{ omit }}"

# If we install packages we need a DNS server working
os_migrate_src_conversion_subnet_dns_nameservers: ['8.8.8.8']
os_migrate_dst_conversion_subnet_dns_nameservers: ['8.8.8.8']

os_migrate_conversion_subnet_name: os_migrate_conv
os_migrate_conversion_subnet_cidr: 192.168.10.0/24
os_migrate_conversion_subnet_alloc_start: 192.168.10.10
os_migrate_conversion_subnet_alloc_end: 192.168.10.99

os_migrate_conversion_delete_fip: true

os_migrate_conversion_router_name: os_migrate_conv
os_migrate_conversion_router_ip: 192.168.10.1

os_migrate_conversion_secgroup_name: os_migrate_conv

os_migrate_conversion_keypair_generate: true
os_migrate_conversion_keypair_name: os_migrate_conv
os_migrate_conversion_keypair_private_path: "{{ os_migrate_data_dir }}/conversion/ssh.key"
os_migrate_conversion_link_keypair_private_path: "{{ os_migrate_data_dir }}/conversion/link-ssh.key"
os_migrate_conversion_host_ssh_user: cloud-user

os_migrate_conversion_host_deploy_timeout: 180
os_migrate_src_conversion_host_boot_from_volume: false
os_migrate_dst_conversion_host_boot_from_volume: false
os_migrate_src_conversion_host_volume_size: 20
os_migrate_dst_conversion_host_volume_size: 20
os_migrate_src_conversion_host_name: os_migrate_conv_src
os_migrate_dst_conversion_host_name: os_migrate_conv_dst
os_migrate_conversion_image_name: os_migrate_conv

os_migrate_conversion_host_content_install: true

os_migrate_conversion_floating_ip_address: false
