namespace: os_migrate
name: os_migrate
version: 0.16.0
readme: README.md
authors:
  - Jiri Stransky <jistr@redhat.com>
  - Carlos Camacho <ccamacho@redhat.com>
  - Ryan Brady <rbrady@redhat.com>
  - Sagi Shnaidman <sshnaidm@redhat.com>
  - Matthew Arnold <marnold@redhat.com>
  # Keep this at the bottom
  - os-migrate (https://github.com/os-migrate)
description: OpenStack tenant migration tooling
license:
  - Apache-2.0
tags:
  - openstack
  - migrations
dependencies:
  community.crypto: '>=1.4.0'
  community.general: '<5.0.0'
  openstack.cloud: '==2.0.0'
repository: 'https://github.com/os-migrate/os-migrate'
homepage: 'https://github.com/os-migrate/os-migrate'
issues: 'https://github.com/os-migrate/os-migrate/issues'
