### REQUIRED

namespace: os_migrate

name: os_migrate

version: 0.1.0

readme: README.md

authors:
  - Jiri Stransky <jistr@redhat.com>
  - Carlos Camacho <ccamacho@redhat.com>
  - Ryan Brady <rbrady@redhat.com>

description: OpenStack tenant migration tooling

license:
  - Apache-2.0

license_file: ''

# A list of tags you want to associate with the
# collection for indexing/searching. A tag name
# has the same character requirements as
# 'namespace' and 'name'
tags: []

dependencies: {}

# The URL of the originating SCM repository
repository: ''

# The URL to any online docs
documentation: ''

# The URL to the homepage of the collection/project
homepage: ''

# The URL to the collection issue tracker
issues: ''
