namespace: os_migrate
name: os_migrate
version: 0.4.1
readme: README.md
authors:
  - Jiri Stransky <jistr@redhat.com>
  - Carlos Camacho <ccamacho@redhat.com>
  - Ryan Brady <rbrady@redhat.com>
  - Sagi Shnaidman <sshnaidm@redhat.com>
  # Keep this at the bottom
  - os-migrate (https://github.com/os-migrate)
description: OpenStack tenant migration tooling
license:
  - Apache-2.0
tags:
  - openstack
  - migrations
dependencies: {}
repository: 'https://github.com/os-migrate/os-migrate'
homepage: 'https://github.com/os-migrate/os-migrate'
issues: 'https://github.com/os-migrate/os-migrate/issues'
