---
# Copyright 2021 os-migrate.
# All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License"); you may
# not use this file except in compliance with the License. You may obtain
# a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
# WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
# License for the specific language governing permissions and limitations
# under the License.

- name: get the current openstacksdk version
  community.general.pip_package_info:
    clients: ['pip', 'pip3']
  register: _installed_openstacksdk

- name: print items for sdk version
  ansible.builtin.debug:
    msg: "{{ _installed_openstacksdk }}"

- name: set openstacksdk version for pip
  ansible.builtin.set_fact:
    _installed_openstacksdk_versions: "{{ _installed_openstacksdk['packages']['pip']['openstacksdk'] | map(attribute='version') | list | first }}"
  when: "_installed_openstacksdk['packages']['pip'] is defined"

- name: set openstacksdk version for pip3
  ansible.builtin.set_fact:
    _installed_openstacksdk_versions: "{{ _installed_openstacksdk['packages']['pip3']['openstacksdk'] | map(attribute='version') | list | first }}"
  when: "_installed_openstacksdk['packages']['pip3'] is defined"

- name: print the current installed version of openstacksdk
  ansible.builtin.debug:
    var: _installed_openstacksdk_versions

- name: fail if the user has an unsupported openstacksdk version
  ansible.builtin.assert:
    that:
      - _installed_openstacksdk_versions is version(os_migrate_common_minimum_openstacksdk_version, '>=')
    fail_msg: |
      The installed openstacksdk version {{ _installed_openstacksdk_versions }}
      must be >= than {{ os_migrate_common_minimum_openstacksdk_version }}
    success_msg: |
      The installed openstacksdk version {{ _installed_openstacksdk_versions }}
      is >= than {{ os_migrate_common_minimum_openstacksdk_version }}

- name: write to auth file
  ansible.builtin.template:
    src: clouds.yaml.j2
    dest: "{{ os_migrate_clouds_path|default(os_migrate_data_dir ~ '/clouds.yaml') }}"
