#!/bin/bash

set -euxo pipefail

if ! virsh pool-list | grep vagrant &> /dev/null; then
    virsh pool-create-as vagrant dir --target $HOME/.local/share/libvirt/vagrant
fi
if ! vagrant box list | grep centos-stream9 &> /dev/null; then
    vagrant box add --name centos-stream9 https://cloud.centos.org/centos/9-stream/x86_64/images/CentOS-Stream-Vagrant-9-latest.x86_64.vagrant-libvirt.box
fi

if ! vagrant plugin list | grep vagrant-libvirt &> /dev/null; then
    vagrant plugin install vagrant-libvirt
fi

vagrant up
