#!/bin/bash

set -euxo pipefail

if ! virsh pool-list | grep vagrant &> /dev/null; then
    virsh pool-create-as vagrant dir --target $HOME/.local/share/libvirt/vagrant
fi
if ! vagrant box list | grep fedora32 &> /dev/null; then
    vagrant box add --name fedora32 https://mirror.karneval.cz/pub/linux/fedora/linux/releases/32/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-32-1.6.x86_64.vagrant-libvirt.box
fi

vagrant up
