#!/bin/bash

set -euxo pipefail

if ! virsh pool-list | grep vagrant &> /dev/null; then
    virsh pool-create-as vagrant dir --target $HOME/.local/share/libvirt/vagrant
fi
if ! vagrant box list | grep fedora36 &> /dev/null; then
    vagrant box add --name fedora36 https://download.fedoraproject.org/pub/fedora/linux/releases/36/Cloud/x86_64/images/Fedora-Cloud-Base-Vagrant-36-1.5.x86_64.vagrant-libvirt.box
fi

vagrant up
