- name: Install epel release
  ansible.builtin.dnf:
    name: epel-release
    state: present

- name: Update all packages
  ansible.builtin.dnf:
    name: '*'
    state: latest
  when: do_yum_update|default(false)|bool

- name: Install content
  ansible.builtin.dnf:
    name:
      - nbdkit
      - nbdkit-basic-plugins
      - qemu-img
      - guestfs-tools
      - libvirt
    state: present

- name: Start libvirtd
  ansible.builtin.service:
    name: libvirtd
    state: started
    enabled: true
