- name: Enable password access in sshd
  ansible.builtin.replace:
    path: /etc/ssh/sshd_config
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'

- name: Reload ssh
  ansible.builtin.service:
    name: sshd
    state: reloaded

- name: Change {{ os_migrate_conversion_host_ssh_user }} password
  ansible.builtin.user:
    name: "{{ os_migrate_conversion_host_ssh_user }}"
    update_password: always
    password: "{{ os_migrate_conversion_host_ssh_user_password|password_hash('sha512') }}"
  no_log: true
