- name: set os_migrate_src_project unless it was set explicitly
  when:
    - os_migrate_src_filter_current_project|default(true)|bool
  block:
    - name: fetch information about currently authenticated user/project
      os_migrate.os_migrate.auth_info:
        cloud: src
        validate_certs: "{{ os_migrate_src_validate_certs|default(omit) }}"
        ca_cert: "{{ os_migrate_src_ca_cert|default(omit) }}"
        client_cert: "{{ os_migrate_src_client_cert|default(omit) }}"
        client_key: "{{ os_migrate_src_client_key|default(omit) }}"
      register: _auth_info

    - name: set os_migrate_src_project_id and os_migrate_src_filters
      ansible.builtin.set_fact:
        os_migrate_src_project_id: "{{ _auth_info.auth_info.project_id }}"
        os_migrate_src_filters:
          project_id: "{{ _auth_info.auth_info.project_id }}"
