- hosts: migrator
  environment:
    OS_CLIENT_CONFIG_FILE: "{{ os_migrate_clouds_path|default(os_migrate_data_dir ~ '/clouds.yaml') }}"
  roles:
    - os_migrate.os_migrate.export_security_groups
    - os_migrate.os_migrate.export_security_group_rules
    - os_migrate.os_migrate.export_images
    - os_migrate.os_migrate.export_projects
    - os_migrate.os_migrate.export_flavors
    - os_migrate.os_migrate.export_users
    - os_migrate.os_migrate.export_user_project_role_assignments
    - os_migrate.os_migrate.export_networks
    - os_migrate.os_migrate.export_subnets
    - os_migrate.os_migrate.export_routers
    - os_migrate.os_migrate.export_router_interfaces
    - os_migrate.os_migrate.export_users_keypairs
    - os_migrate.os_migrate.export_keypairs
