---
galaxy_info:
  author: os-migrate
  role_name: conversion_host
  description: os-migrate resource
  company: Red Hat
  license: Apache-2.0
  min_ansible_version: "2.9"
  platforms:
    - name: Fedora
      versions:
        - "34"
  galaxy_tags: ["osmigrate"]
dependencies:
  - role: os_migrate.os_migrate.prelude_src
  - role: os_migrate.os_migrate.prelude_dst
