- name: Create the keypair folder
  ansible.builtin.file:
    path: "{{ os_migrate_conversion_keypair_private_path | dirname }}"
    state: directory
    mode: '0700'

- name: Generate a keypair for the conversion host
  ansible.builtin.shell: >
    ssh-keygen -t {{ os_migrate_conversion_host_ssh_key_type }}
    {% if os_migrate_conversion_host_ssh_key_type != 'ed25519' %}-b {{ os_migrate_conversion_host_ssh_key_bits }}{% endif %}
    -f "{{ os_migrate_conversion_keypair_private_path }}" -N ""
  args:
    creates: "{{ os_migrate_conversion_keypair_private_path }}"
