#FIXME review! these are duplicated variables from the import workloads role
os_migrate_conversion_keypair_private_path: "{{ os_migrate_data_dir }}/conversion/ssh.key"
os_migrate_timeout: 1800
os_migrate_volume_cleanup_on_failure: true
os_migrate_volume_boot_volume_prefix: os-migrate-
os_migrate_volume_stop_before_migration: false
os_migrate_volumes_data_copy: true
os_migrate_detached_volumes_filter:
  - regex: .*
