- name: read routers resource file
  os_migrate.os_migrate.read_resources:
    path: "{{ os_migrate_data_dir }}/routers.yml"
  register: read_routers

- name: filter routers to import
  ansible.builtin.set_fact:
    filtered_routers: "{{ (
      read_routers.resources
        | os_migrate.os_migrate.stringfilter(os_migrate_routers_filter,
                                             attribute='params.name') ) }}"

- name: import routers
  os_migrate.os_migrate.import_router:
    cloud: dst
    data: "{{ item }}"
    filters: "{{ os_migrate_dst_filters }}"
    validate_certs: "{{ os_migrate_dst_validate_certs|default(omit) }}"
    ca_cert: "{{ os_migrate_dst_ca_cert|default(omit) }}"
    client_cert: "{{ os_migrate_dst_client_cert|default(omit) }}"
    client_key: "{{ os_migrate_dst_client_key|default(omit) }}"
  loop: "{{ filtered_routers }}"
