---
name: Collection Certification Checks

on:
  pull_request:
    branches: [main]
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

concurrency:
  group: cert-ver-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  certification:
    name: Ansible Collection Certification
    uses: ansible-collections/partner-certification-checker/.github/workflows/certification-reusable.yml@v0.1.0
